# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 07:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rq', '0003_question_asker'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='assignee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_assignee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='asker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_asker', to=settings.AUTH_USER_MODEL),
        ),
    ]
